workflows:
  hello-world:
    scripts:
    - name: Set up local properties # required for Android build
      script: |
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

    - name: Build Android  scan     # for building in debug mode
      script: |
        cd android
        ./gradlew assembleDebug    

    - name: Build iOS         # for building iOS (.ipa)
      script: |
        xcode-project use-profiles
        xcode-project build-ipa --workspace "ios/MyReact.xcworkspace" --scheme "MyReact"    
